Добавление файлов для митапа от 07.10.2020
funbox/talks pull request #10
Opened 2020-10-12 06:21 UTC by gongled

2020-10-12 06:55 UTC, igoradamenko requested changes

2020-10-12 06:55 UTC, igoradamenko commented on README.md
> +  Про основные концепции NixOS и пакетного менеджера nix.
Тут какое-то слишком капитанское описание получается. Может, поменяем?

2020-10-12 06:55 UTC, igoradamenko commented on README.md
> +  Про то, как как проводить рефакторинг и перестать его бояться.
«как» задвоился.

2020-10-12 06:55 UTC, igoradamenko commented on meetups/2020-10-07-mixed/01-nix/README.md
> +**[Посмотреть на Ютубе](https://youtu.be/1oJzY6uoFWs)**
«This video is private.»

Так надо?

2020-10-12 09:08 UTC, gongled commented on meetups/2020-10-07-mixed/01-nix/README.md
> +**[Посмотреть на Ютубе](https://youtu.be/1oJzY6uoFWs)**
Да.

2020-10-12 09:13 UTC, gongled commented on README.md
> +  Про то, как как проводить рефакторинг и перестать его бояться.
Поправил (19da712).

2020-10-13 10:25 UTC, dissimulazione approved these changes

2020-10-13 10:25 UTC, dissimulazione commented on README.md
> +### Митап, 7 октября
Вот тут, может, придумаем какое-то универсальное название для обычных внутренних митапов без заданной темы? «Внутренний митап FunBox», например.

2020-10-13 10:25 UTC, merged