Добавление инструкции по работе с репозиторием
funbox/talks pull request #9
Opened 2020-10-08 11:39 UTC by igoradamenko

Расписал максимально подробно всё, что кажется важным.

Можно было бы подготовить какое-то короткое описание, однако, предполагаю, что репозиторий в будущем будет вести 2-3 человека, и каждый из них просто один раз прочитает гайд, и сразу начнёт делать «как надо». Потому, что уж тут мелочиться, надо расписать всё!

2020-10-08 13:32 UTC, dissimulazione requested changes

2020-10-08 13:32 UTC, dissimulazione commented on CONTRIBUTING.md
> +Чтобы облегчить работу с ним в будущем, в этом файле описано, каких правил мы придерживаемся при оформлении репозитория.
С репозиторием, иначе теряется контекст и не сразу понятно, о чём речь.

2020-10-08 13:32 UTC, dissimulazione commented on CONTRIBUTING.md
> +Мы ожидаем, что при добавлении новой информации, вы:
Запятая не нужна.

2020-10-08 13:32 UTC, dissimulazione commented on CONTRIBUTING.md
> +1. Форкните этот репозиторий, если у вас нет прав на запись в него.
Не нужно, права на запись у всех, кто будет работать с репозиторием, точно будут.

2020-10-08 13:32 UTC, dissimulazione commented on CONTRIBUTING.md
> +Если вы всё сделали, как описано выше, то после проверки и обсуждений **[@dissimulazione](https://github.com/dissimulazione)** смержит правки.
Вот тут лучше дать ссылку на ментейнера в виде файла в самой репе, потому что не факт, что это всегда буду я. Лучше хранить в одном месте, чтобы там можно было поменять в случае чего и не думать, где ещё оно упоминается.

2020-10-08 13:32 UTC, dissimulazione commented on CONTRIBUTING.md
> +Мы ожидаем, что при добавлении новой информации, вы:
Вообще, кажется, что можно этот раздел слить с тем, что дальше — именование веток это скорее детали, а то, что мы ожидаем, что автор будет коммитить и потом создаст PR, и так понятно, вроде. Можно это описать просто как порядок шагов воркфлоу, а не как наши ожидания.

2020-10-08 13:32 UTC, dissimulazione commented on CONTRIBUTING.md
> +Первым делом, если вам нужно добавить или удалить информацию о каком-то выступлении, необходимо установить Git LFS:
Вот это не совсем так. LFS нужен только для PDF и прочих тяжелых файлов, чтобы просто поправить ридми, можно и без него.

2020-10-08 13:32 UTC, dissimulazione commented on CONTRIBUTING.md
> +  Слова вроде «митап», «конференция» и пр. из названия нужно убирать, т. к. и так понятно, о чём речь.
Скорее, не нужно добавлять — мы же сами название придумываем.

2020-10-08 13:32 UTC, dissimulazione commented on CONTRIBUTING.md
> +В общем случае, шаблон этого файла примерно такой:
В абстрактном виде сложно воспринимать, хочется помимо разметки ещё реальный пример результата увидеть, так будет нагляднее.

2020-10-08 13:32 UTC, dissimulazione commented on CONTRIBUTING.md
> +В README.md внутри папки с докладом стоит придерживаться следующего шаблона:
Возможно, «нужно» вместо «стоит»? А то как-то не очень явно, может, и не стоит?

2020-10-08 13:32 UTC, dissimulazione commented on CONTRIBUTING.md
> +> Андрей рассказывает о...
Вот тут лучше добавить фамилий, как на самом деле.

2020-10-08 13:32 UTC, dissimulazione commented on CONTRIBUTING.md
> +Иногда в докладах бывают ещё какие-то сопутствующие материалы. Например, документ с чеклистом.
Может, прямо ссылку дать?

2020-10-08 14:33 UTC, igoradamenko commented on CONTRIBUTING.md
> +Чтобы облегчить работу с ним в будущем, в этом файле описано, каких правил мы придерживаемся при оформлении репозитория.
Поменял местами «его» и «репозиторий», смотри.

2020-10-08 14:33 UTC, igoradamenko commented on CONTRIBUTING.md
> +Мы ожидаем, что при добавлении новой информации, вы:
Переделал на более повелительный список, без ожиданий.

2020-10-08 14:34 UTC, igoradamenko commented on CONTRIBUTING.md
> +1. Форкните этот репозиторий, если у вас нет прав на запись в него.
Исправил.

2020-10-08 14:34 UTC, igoradamenko commented on CONTRIBUTING.md
> +Если вы всё сделали, как описано выше, то после проверки и обсуждений **[@dissimulazione](https://github.com/dissimulazione)** смержит правки.
Сделал в каком-то виде.

2020-10-08 14:35 UTC, igoradamenko commented on CONTRIBUTING.md
> +Первым делом, если вам нужно добавить или удалить информацию о каком-то выступлении, необходимо установить Git LFS:
Справедливо. Пока написал только про PDF. «Прочие тяжёлые файлы» ещё надо отдельно добавлять в Git LFS, так что, их наверное тут не стоит упоминать.

2020-10-08 14:36 UTC, igoradamenko commented on CONTRIBUTING.md
> +  Слова вроде «митап», «конференция» и пр. из названия нужно убирать, т. к. и так понятно, о чём речь.
Не обязательно же. Может быть какой-нибудь Noname Ruby Meetup. Сейчас мы придерживаемся того, чтобы пути были `meetups/2020-02-20/noname-ruby`.

2020-10-08 14:36 UTC, igoradamenko commented on CONTRIBUTING.md
> +В общем случае, шаблон этого файла примерно такой:
Добавил пример результата, спрятал его под спойлер.

2020-10-08 14:37 UTC, igoradamenko commented on CONTRIBUTING.md
> +В README.md внутри папки с докладом стоит придерживаться следующего шаблона:
Мне кажется, что эта часть не должна быть особо регламентированной. Когда-нибудь мы сами захотим её нарушить красоты ради. Потому, пусть будет «стоит». Всё равно перед мержем будет ревью.

2020-10-08 14:38 UTC, igoradamenko commented on CONTRIBUTING.md
> +> Андрей рассказывает о...
А на самом деле фамилий-то и нет.

> Глеб делает прогнозы развития протокола HTTP и обсуждаемых новинок в IETF HTTPWG. 

> Глеб и Дмитрий рассказывают, почему важно следить за содержанием углекислого газа в воздухе и как можно его контролировать.

> Глеб делится опытом агрегации и обработки логов Nginx в инфраструктуре компании с хранением метрик в ClickHouse.

> Алексей рассказывает о SRE: как и когда появилось, а также зачем такая практика может понадобиться. 

И так далее.

2020-10-08 14:40 UTC, igoradamenko commented on CONTRIBUTING.md
> +Иногда в докладах бывают ещё какие-то сопутствующие материалы. Например, документ с чеклистом.
Дал.

2020-10-08 14:41 UTC, igoradamenko commented
@dissimulazione, запушил фиксап-коммит. Не забудь пнуть меня перед мержем, чтобы я слил их.

2020-10-09 10:29 UTC, dissimulazione approved these changes

2020-10-09 10:29 UTC, dissimulazione commented on CONTRIBUTING.md
> +3. Создайте PR из своей ветки (и форка, если он есть) в `master` этого репозитория. Из названия PR должно быть понятно, о чём он (смотрите [историю смерженных PR](https://github.com/funbox/talks/pull
Про форк видимо лишнее осталось.

2020-10-09 10:29 UTC, dissimulazione commented on CONTRIBUTING.md
> +> Андрей рассказывает о...
А, точно, там же автор сверху указан, ага, норм.

2020-10-09 10:29 UTC, merged